### ISSUE TITLE
What means "self.bert_arg = bert_model.get_sequence_output()"?

### ISSUE THREAD

**Issue by zysNLP** [chunjy92/drsc#1]
Notice in your "drsc/embedding/BERTEmbedding.py" line 236, you get self.bert_arg.shape=[batch_size, arg_len*2, hidden_size] after series of tf.concat. I want to know what does these self.bert_args mean before and after concat?

**Comment by chunjy92** [comment]
Sorry for the delay in response, didn't see it until now.

Since Arg1 and Arg2 are concatenated before it is fed into BERT, you can argue that (1) before concat, we have two separate placeholders for Arg1 and Arg2, and (2) after concat, a single representation of Arg1+Arg2 serves as an input to the BERT, whose output is `bert_arg` that you are mentioning.

**Comment by zysNLP** [comment]
OK，Thank you very much, and could you please add some contents in readme? It seem to be a useful work like make bert more easy, but less some introduction.

**Comment by chunjy92** [comment]
As you might can probably tell, I'm not actively maintaining this repo. But yes, I will try to update the README soon.
